public open class Enemy(
    agility: UInt,
    damageResistance: UInt,
    experiencePoints: UInt,
    goldPoints: UInt,
    hitPoints: UInt,
    magicPoints: UInt,
    name: String,
    statusResistance: UInt,
    strength: UInt,
) : NPC(
    agility = agility,
    damageResistance = damageResistance,
    experiencePoints = experiencePoints,
    goldPoints = goldPoints,
    hitPoints = (hitPoints.toInt() - (((0..256).random() * hitPoints.toInt()) shr 10)).toUInt(),
    magicPoints = magicPoints,
    name = name,
    statusResistance = statusResistance,
    strength = strength,
)
